### ISSUE TITLE
name 'config' is not defined

### ISSUE THREAD

**Issue by afonsomv** [google-marketing-solutions/abcds-detector#19]
## Expected Behavior
Running the colab and getting an LLM evaulation
## Actual Behavior
Since today, When running the colab with the exact same parameters and Video of yesterday (7/11/24), the code gets the image error and is not able to make the LLM evalutation. 

Why is thins happening? Was there any relevant change? 

![image](https://github.com/user-attachments/assets/802279a0-46fc-4325-8935-4f1fbe1152aa)

**Comment by anaesqueda** [comment]
Hi Alfonso, the issue has been resolved.

Please create a new copy of the colab. Feel free to reach out if you have any questions.

Thanks!

**Comment by afonsomv** [comment]
Hello, Ana

Thank you so much for your information. However, I'm still seeing a
general exception:

[image: image.png]

What is the cause of it? Is it something related with the inputs I gave, in
the colab?

Thank you
