### ISSUE TITLE
Regarding the issue of ABCDs detector

### ISSUE THREAD

**Issue by BinuraYasodya** [google-marketing-solutions/abcds-detector#7]
I am experiencing a persistent 500 Internal Server Error while executing API calls within my Google Cloud project. This error occurs specifically when invoking certain Google Cloud services, and the error message indicates an internal server issue.

Details:
Error Message: 500 Internal Error encountered.
Error Type: _InactiveRpcError
Status Code: StatusCode.INTERNAL
Debug Error String: UNKNOWN:Error received from peer ipv4:[74.125.200.95:443](http://74.125.200.95:443/) {created_time:"2024-08-15T09:46:34.682963656+00:00", grpc_status:13, grpc_message:"Internal error encountered."}

Context:
The error arises when executing the detect_quick_pacing function within my Python application. This function is used to process and analyze video files stored in Google Cloud Storage.

The function involves interacting with various Google Cloud APIs, including video processing and machine learning services.

I have verified that the bucket name, video URIs, and all relevant configurations are correct.

The issue seems to be unrelated to the size of the video files or the specific dataset being used, as the error occurs consistently.

Troubleshooting Steps Taken:
Verified Google Cloud service status and found no ongoing outages.
Double-checked API quotas and limits to ensure compliance.
Implemented additional logging and exception handling in my code.
Attempted retries with exponential backoff.
Ensured all libraries and dependencies are up to date
.
Given these circumstances, I am requesting your assistance in diagnosing and resolving this issue. Could you please provide guidance on:

Possible causes of the 500 Internal Server Error in this context.
Steps to further troubleshoot or resolve the issue.
Any additional logs or information you may require from my side.
Your prompt assistance in this matter would be greatly appreciated, as it is crucial for the timely execution of our video analysis tasks.

Thank you for your support.
![error](https://github.com/user-attachments/assets/5afecbbe-9ba7-42e9-a041-c643d12bd4db)
![Place](https://github.com/user-attachments/assets/b9189b34-caa0-4a82-a5ae-51c5eeef16a1)

**Comment by pkenjora** [comment]
Hi, this issue is related to the way the new vertex AI throws quota exceptions.  Its happening on that call because thats when y the code hits the quota limit.  We have reproduced this and patched it on the **paul_changes** branch. We'll be merging into main in the future.
